import img1 from "../images/img1.jpg"
import img2 from "../images/img2.jpg"
import img3 from "../images/img3.jpg"
import img4 from "../images/img4.jpg"
import img5 from "../images/img5.jpg"
import img6 from "../images/img6.jpg"
import img7 from "../images/img7.jpg"
import img8 from "../images/img8.jpg"
export const Most = [
  {
    id: 1,
    img: img1,
    avreg: "4.3",
    iconaverg: "fa fa-star",
    namegame: "Fortnite",
    dawon: "Sandbox",
    icondawolode: "fa fa-download",
    avregdawonlode: "1.4M",
  },
  {
    id: 2,
    img: img2,
    avreg: "9.3",
    iconaverg: "fa fa-star",
    namegame: "PubG",
    dawon: "Battle S",
    icondawolode: "fa fa-download",
    avregdawonlode: "1.9M",
  },
  {
    id: 3,
    img: img3,
    avreg: "8.2",
    iconaverg: "fa fa-star",
    namegame: "Dota2",
    dawon: "Steam-X",
    icondawolode: "fa fa-download",
    avregdawonlode: "3.6M",
  },
  {
    id: 4,
    img: img4,
    avreg: "1.2",
    iconaverg: "fa fa-star",
    namegame: "CS-GO",
    dawon: "Legendary",
    icondawolode: "fa fa-download",
    avregdawonlode: "15.6K",
  },
  {
    id: 5,
    img: img5,
    avreg: "0.2",
    iconaverg: "fa fa-star",
    namegame: "Mini Craft",
    dawon: "Legendary",
    icondawolode: "fa fa-download",
    avregdawonlode: "3.6K",
  },
  {
    id: 6,
    img: img6,
    avreg: "3.2",
    iconaverg: "fa fa-star",
    namegame: "Eagles Fly",
    dawon: "Matrix Games",
    icondawolode: "fa fa-download",
    avregdawonlode: "8.6M",
  },
  {
    id: 7,
    img: img7,
    avreg: "1.6",
    iconaverg: "fa fa-star",
    namegame: "Warface",
    dawon: "Max 3D",
    icondawolode: "fa fa-download",
    avregdawonlode: "3.1M",
  },
  {
    id: 8,
    img: img8,
    avreg: "0.6",
    iconaverg: "fa fa-star",
    namegame: "Warcraft",
    dawon: "Legend",
    icondawolode: "fa fa-download",
    avregdawonlode: "10.1K",
  },
  {
    id: 9,
    img: img1,
    avreg: "4.3",
    iconaverg: "fa fa-star",
    namegame: "Fortnite",
    dawon: "Sandbox",
    icondawolode: "fa fa-download",
    avregdawonlode: "103.4K",
  },
  {
    id: 10,
    img: img2,
    avreg: "9.3",
    iconaverg: "fa fa-star",
    namegame: "PubG",
    dawon: "Battle S",
    icondawolode: "fa fa-download",
    avregdawonlode: "1.4M",
  },
  {
    id: 11,
    img: img3,
    avreg: "8.2",
    iconaverg: "fa fa-star",
    namegame: "Dota2",
    dawon: "Steam-X",
    icondawolode: "fa fa-download",
    avregdawonlode: "3.6M",
  },
  {
    id: 12,
    img: img4,
    avreg: "1.2",
    iconaverg: "fa fa-star",
    namegame: "CS-GO",
    dawon: "Legendary",
    icondawolode: "fa fa-download",
    avregdawonlode: "15.6K",
  },
  {
    id: 13,
    img: img5,
    avreg: "0.2",
    iconaverg: "fa fa-star",
    namegame: "Mini Craft",
    dawon: "Legendary",
    icondawolode: "fa fa-download",
    avregdawonlode: "3.6K",
  },
  {
    id: 14,
    img: img6,
    avreg: "3.2",
    iconaverg: "fa fa-star",
    namegame: "Eagles Fly",
    dawon: "Matrix Games",
    icondawolode: "fa fa-download",
    avregdawonlode: "8.6M",
  },
  {
    id: 15,
    img: img7,
    avreg: "1.6",
    iconaverg: "fa fa-star",
    namegame: "Warface",
    dawon: "Max 3D",
    icondawolode: "fa fa-download",
    avregdawonlode: "3.1M",
  },
]; 