import stream05 from "../images/stream05.jpg";
import stream06 from "../images/stream06.jpg";
import stream07 from "../images/stream07.jpg";
import stream08 from "../images/stream08.jpg";
import avatar01 from "../images/avatar01.jpg";
import avatar02 from "../images/avatar02.jpg";
import avatar03 from "../images/avatar03.jpg";
import avatar04 from "../images/avatar04.jpg";

export const LiveSreame = [
  {
    id: 1,
    img_main: stream05,
    img_live: "Live",
    img_avreg: "1.2",
    img_iconavreg: "fa fa-eye",
    img_namegame: "CS.GO",
    img_iconnamegame: "fa fa-gamepad",
    img: avatar01,
    icon: "fa fa-check",
    iconspan: "KenganC",
    des: "Just Talking With Fans",
  },
  {
    id: 2,
    img_main: stream06,
    img_live: "Live",
    img_avreg: "1.2",
    img_iconavreg: "fa fa-eye",
    img_namegame: "CS.GO",
    img_iconnamegame: "fa fa-gamepad",
    img: avatar02,
    icon: "fa fa-check",
    iconspan: "LunaMa",
    des: "CS-GO 36 Hours Live Stream",
  },
  {
    id: 3,
    img_main: stream07,
    img_live: "Live",
    img_avreg: "1.2",
    img_iconavreg: "fa fa-eye",
    img_namegame: "CS.GO",
    img_iconnamegame: "fa fa-gamepad",
    img: avatar03,
    icon: "fa fa-check",
    iconspan: "Areluwa",
    des: "Maybe Nathej Allnight Chillin'",
  },
  {
    id: 4,
    img_main: stream08,
    img_live: "Live",
    img_avreg: "1.2",
    img_iconavreg: "fa fa-eye",
    img_namegame: "CS.GO",
    img_iconnamegame: "fa fa-gamepad",
    img: avatar04,
    icon: "fa fa-check",
    iconspan: "GangTm",
    des: "Live Streaming Till Morning",
  },
  {
    id: 6,
    img_main: stream06,
    img_live: "Live",
    img_avreg: "1.2",
    img_iconavreg: "fa fa-eye",
    img_namegame: "CS.GO",
    img_iconnamegame: "fa fa-gamepad",
    img: avatar02,
    icon: "fa fa-check",
    iconspan: "LunaMa",
    des: "CS-GO 36 Hours Live Stream",
  },
  
  {
    id: 8,
    img_main: stream08,
    img_live: "Live",
    img_avreg: "1.2",
    img_iconavreg: "fa fa-eye",
    img_namegame: "CS.GO",
    img_iconnamegame: "fa fa-gamepad",
    img: avatar04,
    icon: "fa fa-check",
    iconspan: "GangTm",
    des: "Live Streaming Till Morning",
  },
  {
    id: 5,
    img_main: stream05,
    img_live: "Live",
    img_avreg: "1.2",
    img_iconavreg: "fa fa-eye",
    img_namegame: "CS.GO",
    img_iconnamegame: "fa fa-gamepad",
    img: avatar01,
    icon: "fa fa-check",
    iconspan: "KenganC",
    des: "Just Talking With Fans",
  },
  {
    id: 9,
    img_main: stream07,
    img_live: "Live",
    img_avreg: "1.2",
    img_iconavreg: "fa fa-eye",
    img_namegame: "CS.GO",
    img_iconnamegame: "fa fa-gamepad",
    img: avatar04,
    icon: "fa fa-check",
    iconspan: "GangTm",
    des: "Live Streaming Till Morning",
  },
];
